### PR TITLE
Update versions and regex requirements

### PR DESCRIPTION
**Pull request by thekaleidoscope**
Updated several pip packages version.
Appeded r in beginning of raw regex in multiple places.

Closes https://github.com/Girbons/comics-downloader/issues/8

### CODE REVIEW

**Comment by Girbons** [comment]
Hey @thekaleidoscope!

Thanks for the contribution. I saw that you upgraded `im2pdf` to the `0.3.1` and the CI fail maybe due to it. Would you like to investigate about it?

**Comment by thekaleidoscope** [comment]
Yep, You were right. Sorry about that.

**Comment by Girbons** [comment]
Requests update has already been merged If you want to update imag2pdf feel free to do it

**Comment by thekaleidoscope** [comment]
Nah, I think there are some conflicts among the packages.

**Pull request closed without merging**
