### PR TITLE
Add MangaKakalot and Manganato support

### PR DESCRIPTION
**Pull request by Jan0660**
Adds support for:
 - [MangaKakalot](https://mangakakalot.com/)
 - [Manganato](https://manganato.com/)

Both are implemented under the same struct since they have pretty much the same document structure except for CSS class names.

### CODE REVIEW

**Review by Girbons — COMMENTED** [review]
Thank you for the PR @Jan0660!

The PR overall is good, just one thing, despite the sites shares the same structure I would separe them in different files 😄

**Comment by Jan0660** [comment]
> Thank you for the PR @Jan0660!
> 
> The PR overall is good, just one thing, despite the sites shares the same structure I would separate them in different files 😄

Fair enough, but where should I put the shared scraping code for the sites? Don't see an existing place in the folder structure for it. Or should I not share the code between them?

**Comment by Girbons** [comment]
> Fair enough, but where should I put the shared scraping code for the sites? Don't see an existing place in the folder structure for it. Or should I not share the code between them?

Yep sharing code is fine, I was thinking about something like `common.go`. What are your thoughts on that?

**Comment by Jan0660** [comment]
> > Fair enough, but where should I put the shared scraping code for the sites? Don't see an existing place in the folder structure for it. Or should I not share the code between them?
> 
> Yep sharing code is fine, I was thinking about something like `common.go`. What are your thoughts on that?

Done! Also added some more tests for both of the sites.

**Pull request merged**
